import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
"use client"; // penting supaya kita boleh guna useRef/useEffect

import { useRef, useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const audioRef = useRef(null);

  useEffect(() => {
    if (audioRef.current) {
      // Try play bila user dah interact
      const playAudio = () => {
        audioRef.current.play().catch(() => {});
        document.removeEventListener("click", playAudio);
      };
      document.addEventListener("click", playAudio);
    }
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Global Background Music */}
        <audio
          ref={audioRef}
          src="/cinnamon.mp3"
          preload="auto"
          loop
          hidden
        />
        {children}
      </body>
    </html>
  );
}
